name = "examples"
version = "0.1.0"
defaultTargets = ["Examples"]

[[require]]
name = "veil"
git = "https://github.com/verse-lab/veil.git"
rev = "main"

[[lean_lib]]
name = "VeilProtocols"
roots = ["VeilProtocols"]

[[lean_lib]]
name = "Examples"
roots = ["Examples"]